export default {
  products: [
    {
      _id: 1,
      title: 'Men Casual Shoe',
      price: '2000.99',
      image: './images/pic1.png',
      rating: 4.5,
      numReviews: 45,
      countInStock: 9,
      description: 'A long story short',
    },
    {
      _id: 2,
      title: 'Men Casual Shoe',
      price: '2000.99',
      image: './images/pic2.png',
      rating: 3,
      numReviews: 10,
      countInStock: 0,
      description: 'A long story short',
    },
    {
      _id: 3,
      title: 'Women Casual Shoe',
      price: '2000.99',
      image: './images/pic3.png',
      rating: 4,
      numReviews: 23,
      countInStock: 5,
      description: 'A long story short',
    },
    {
      _id: 4,
      title: 'Men Casual Shoe',
      price: '2000.99',
      image: './images/pic4.png',
      rating: 2.5,
      numReviews: 19,
      countInStock: 2,
      description: 'A long story short',
    },
    {
      _id: 5,
      title: 'Men Casual Shoe',
      price: '2000.99',
      image: './images/pic5.png',
      rating: 5,
      numReviews: 65,
      countInStock: 4,
      description: 'A long story short',
    },
    {
      _id: 6,
      title: 'Men Casual Shoe',
      price: '2000.99',
      image: './images/pic6.png',
      rating: 4.5,
      numReviews: 50,
      countInStock: 1,
      description: 'A long story short',
    },
    {
      _id: 5,
      title: 'Men Casual Shoe',
      price: '2000.99',
      image: './images/pic7.png',
      rating: 1.5,
      numReviews: 35,
      countInStock: 7,
      description: 'A long story short',
    },
    {
      _id: 7,
      title: 'Men Casual Shoe',
      price: '2000.99',
      image: './images/pic8.png',
      rating: 3.5,
      numReviews: 95,
      countInStock: 1,
      description: 'A long story short',
    },
  ],
};
